name: CD Frontend build

on:
  workflow_run:
    workflows: ["Development CI"]
    types: ["completed"]on:
on:
  workflow_run:
    workflows: ["Development CI"]
    types: ["completed"]
    branches: [ "dev", "stage", "main" ]

jobs:
  make-dev-builds:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 24

  
      - name: Install dependencies
        run: npm ci

      - name: Get app metadata
        shell: bash
        run: |
          echo "APP_NAME=$(node -p \"require('./package.json').name\")" >> $GITHUB_ENV
          echo "APP_VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Vite app
        run: npm run build

      - name: Build Electron app
        run: npm run dist

      - name: Prepare release artifacts (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p release
          for file in dist/*; do
            if [ -f "$file" ]; then
              ext="${file##*.}"
              new_name="${APP_NAME}-${APP_VERSION}-${GIT_SHA}-${{ matrix.os }}.${ext}"
              cp "$file" "release/$new_name"
            fi
          done

      - name: Prepare release artifacts (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force release | Out-Null
          Get-ChildItem dist | ForEach-Object {
            $ext = $_.Extension
            $newName = "$env:APP_NAME-$env:APP_VERSION-$env:GIT_SHA-${{ matrix.os }}$ext"
            Copy-Item $_.FullName "release\$newName"
          }
        
  build-and-deploy-docker-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: randomdegen/ppit-gateway:latest
          target: prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
